spring:
  datasource:
    #mysql8.0 以上需要这个驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: gyy19930719
    url: jdbc:mysql://localhost:3306/gyy?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B8
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml